## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
##urlDB: jdbc:mysql://localhost:3306/baselocal?useSSL=false
##userDB: root
##passDB: adminq
urlDB: jdbc:mysql://qyw391.marfilgrupo.es:3306/qyw391?useSSL=false
userDB: qyw391
passDB: Descargar1
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
minutosParaValidar: 4320
longitudCodigo: 50
minutos: -10